#stage 1
FROM node:10-alpine as build-step
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN npm run postinstall --prod
RUN cp /app/app/src/main/xenia-prod.js /app/app/src/main/xenia.js


## Stage 2
FROM nginx:1.19.2
COPY --from=build-step /app/app /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf.template /etc/nginx/conf.d/default.conf.template
COPY htpasswd /etc/apache2/.htpasswd
CMD /bin/bash -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'

