spring:
  application:
    name: xenia-api2

  datasource:
    url: jdbc:h2:file:./xeniadb;DB_CLOSE_ON_EXIT=FALSE
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:file:./xeniadb;DB_CLOSE_ON_EXIT=FALSE
      data-username: sa
      data-password:
      driver-class-name: org.h2.Driver
      database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: heroku
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: ${DATABASE_URL}

