spring:
  application:
    name: xenia-api2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./xeniadb;DB_CLOSE_ON_EXIT=FALSE
    data-username: sa
    data-password:

    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
